In [1]:
import pandas as pd
import sqlite3

In [2]:
products = pd.read_csv("../data/processed/products_clean.csv")
reviews = pd.read_csv("../data/processed/skincare_reviews_clean.csv")

/var/folders/gw/b8128pz11k31ky_873j0sxsc0000gn/T/ipykernel_49299/3630865940.py:2: DtypeWarning: Columns (0: author_id) have mixed types. Specify dtype option on import or set low_memory=False.
  reviews = pd.read_csv("../data/processed/skincare_reviews_clean.csv")

In [3]:
conn = sqlite3.connect("../data/processed/beautyiq.db")

In [4]:
products.to_sql(
    "products",
    conn,
    if_exists="replace",
    index=False
)

8494

In [5]:
reviews.to_sql(
    "reviews",
    conn,
    if_exists="replace",
    index=False,
    chunksize=50000
)

1092967

In [6]:
pd.read_sql_query(
    "SELECT COUNT(*) AS product_count FROM products",
    conn
)

   product_count
0           8494

In [7]:
pd.read_sql_query(
    "SELECT COUNT(*) AS review_count FROM reviews",
    conn
)

   review_count
0       1092967

In [8]:
conn.close()